### ISSUE TITLE
Assertion error while rendering mask (java.lang.IllegalArgumentException: w and h must be > 0)

### ISSUE THREAD

**Issue by VISTALL** [weisJ/jsvg#79] opened 2024-06-05 12:44 UTC
Hello :)

Sample project [untitled.zip](https://github.com/user-attachments/files/15587039/untitled.zip)

Video ![bugSVG](https://github.com/weisJ/jsvg/assets/542934/4c9bed26-7951-4160-9ad6-e7670e5ebcb7)

Step for reproduce:
 * Start App class
 * Select last visible item
 * Try to resize window 

Exception
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: w and h must be > 0
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:214)
	at java.desktop/java.awt.image.ComponentColorModel.createCompatibleWritableRaster(ComponentColorModel.java:2809)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:420)
	at com.github.weisj.jsvg.util.ImageUtil.createLuminosityBuffer(ImageUtil.java:60)
	at com.github.weisj.jsvg.util.BlittableImage.create(BlittableImage.java:90)
	at com.github.weisj.jsvg.nodes.Mask.createMaskPaint(Mask.java:94)
	at com.github.weisj.jsvg.renderer.NodeRenderer.lambda$createRenderInfo$0(NodeRenderer.java:138)
	at com.github.weisj.jsvg.renderer.Graphics2DOutput.setPaint(Graphics2DOutput.java:81)
	at com.github.weisj.jsvg.renderer.NodeRenderer.createRenderInfo(NodeRenderer.java:138)
	at com.github.weisj.jsvg.renderer.NodeRenderer.renderNode(NodeRenderer.java:101)
	at com.github.weisj.jsvg.nodes.container.CommonRenderableContainerNode.render(CommonRenderableContainerNode.java:81)
	at com.github.weisj.jsvg.nodes.container.BaseInnerViewContainer.renderWithSize(BaseInnerViewContainer.java:140)
	at com.github.weisj.jsvg.nodes.container.BaseInnerViewContainer.renderWithSize(BaseInnerViewContainer.java:82)
	at com.github.weisj.jsvg.SVGDocument.renderWithPlatform(SVGDocument.java:108)
	at com.github.weisj.jsvg.SVGDocument.render(SVGDocument.java:80)
	at untitled.App$1$1.paintIcon(App.java:49)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:191)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:170)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:293)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:383)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:306)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5325)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1114)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3959)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:889)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by VISTALL** [comment] 2024-06-05 12:46
```
new ViewBox(2, 2, getIconWidth(), getIconHeight())
```

can replaced by 
```
new ViewBox(x, y, getIconWidth(), getIconHeight())
```

but error persist

**Comment by weisJ** [comment] 2024-06-05 21:44
Probably some masks/elements with a mask that have an effective size with at least one dimension 0. They shouldn’t be painted in the first place.

As an immediate solution you can try to bake in the masks into your icons.

**Comment by weisJ** [comment] 2024-06-06 14:25
Could not reproduce. Might be already fixed with the latest snapshot. Can you test if the issue disappears with the snapshot version?

**Comment by VISTALL** [comment] 2024-06-06 15:08
Hello. I will build the library from source, and test it

**Comment by weisJ** [comment] 2024-06-06 15:12
You don't have to build from source. The snapshots are published on https://oss.sonatype.org/content/repositories/snapshots/

**Comment by VISTALL** [comment] 2024-06-06 15:13
Thanks! Can you say last snapshot version?

**Comment by weisJ** [comment] 2024-06-06 15:16
It is documented in the README. For cradle it is "com.github.weisj:jsvg:latest.integration". It probably also works for Maven. Otherwise you can try "com.github.weisj:jsvg:SNAPSHOT"

**Comment by VISTALL** [comment] 2024-06-06 15:19
Found. 1.5.0-SNAPSHOT. And you are rights. Impossible to reproduce now. When you will release the next version of library?

**Comment by weisJ** [comment] 2024-06-07 09:32
Soon

**Comment by weisJ** [comment] 2024-06-07 13:44
Version 1.5.0 has been released

**Closed by weisJ** 2024-06-07 13:44 UTC
Labels: bug

**Comment by VISTALL** [comment] 2024-06-07 13:48
Thanks you :)
