### ISSUE TITLE
Gray Filter for SVGs (Eclipse Icons) Not Working for Some Icons

### ISSUE THREAD

**Issue by Michael5601** [weisJ/jsvg#97] opened 2024-11-20 13:54 UTC
I attempted to introduce a gray filter to my SVGs (Eclipse Icons) at runtime to give them a "disabled look". While this worked well for most icons, some did not get rasterized as expected. To investigate, I rasterized the faulty icons using Chrome, and it had no issues.

Unfortunately, I couldn't determine which specific combination of SVG elements causes the problem. Perhaps you can help identify the cause. Below, I’ve provided links to both the icons that work and those that don’t.

### The Introduced Filter

I added the following filter as a new child element within the existing `<defs>` tag:

```xml
<filter id="disabledLook">
    <!-- Grayscale conversion -->
    <feColorMatrix type="saturate" values="0"/>

    <!-- Additional desaturation -->
    <feComponentTransfer>
        <feFuncR type="linear" slope="0.8" />
        <feFuncG type="linear" slope="0.8" />
        <feFuncB type="linear" slope="0.8" />
    </feComponentTransfer>

    <!-- Brightness and contrast adjustment -->
    <feComponentTransfer>
        <feFuncR type="linear" slope="0.8" intercept="0.1" />
        <feFuncG type="linear" slope="0.8" intercept="0.1" />
        <feFuncB type="linear" slope="0.8" intercept="0.1" />
    </feComponentTransfer>
</filter>
```

To activate this filter, I added the following property to the `<svg>` element:

```xml
filter="url(#disabledLook)"
```

### Icons That Were Rasterized Successfully

1. [start.svg](https://github.com/eclipse-platform/eclipse.platform.images/blob/master/org.eclipse.images/eclipse-svg/org.eclipse.e4.tools.bundle.spy/icons/start.svg)
2. [external_tools.svg](https://github.com/eclipse-platform/eclipse.platform.images/blob/master/org.eclipse.images/eclipse-png/org.eclipse.ui.externaltools/full/obj16/external_tools.png)

### Icons That Failed (Filter Not Applied)

1. [package_obj.svg](https://github.com/eclipse-platform/eclipse.platform.images/blob/master/org.eclipse.images/eclipse-svg/org.eclipse.pde.ui/icons/elcl16/package_obj.svg)
2. [newclass_wiz.svg](https://github.com/eclipse-platform/eclipse.platform.images/blob/master/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/etool16/newclass_wiz.svg)

**Comment by weisJ** [comment] 2024-11-20 14:22
Minimal reproducing version:
````xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
    <defs>
        <filter id="disabledLook">
            <!-- Grayscale conversion -->
            <feColorMatrix type="saturate" values="0"/>

            <!-- Additional desaturation -->
            <feComponentTransfer>
                <feFuncR type="linear" slope="0.8"/>
                <feFuncG type="linear" slope="0.8"/>
                <feFuncB type="linear" slope="0.8"/>
            </feComponentTransfer>

            <!-- Brightness and contrast adjustment -->
            <feComponentTransfer>
                <feFuncR type="linear" slope="0.8" intercept="0.1"/>
                <feFuncG type="linear" slope="0.8" intercept="0.1"/>
                <feFuncB type="linear" slope="0.8" intercept="0.1"/>
            </feComponentTransfer>
        </filter>
    </defs>
    <g filter="url(#disabledLook)">
        <rect fill="red" x="0%" y="0%" width="100%" height="100%"/>
        <g transform=""/>
    </g>
</svg>
````

**Comment by weisJ** [comment] 2024-11-20 14:51
Issue is due to incorrect computation of bounds of empty groups with a transform. I have a fix for this, but releasing it will take a bit as I am currently working on getting animation support to a releasable state.
If you remove all of the empty groups then the filter will work fine.

PS: You can simplify the filter by combining both component transfers into a single transfer with slop 0.64 and intercept 0.1

**Comment by Michael5601** [comment] 2024-11-20 15:27
Thats great! Thanks a lot for this quick response. No worries with the fix, I will clean up the SVGs that are not working.

**Closed** 2024-11-26 21:58 UTC
Labels: bug
